<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-ORUDN72" failures="1" tests="1" name="144. AccountingReports  -------- VerifyPLTotalTrialBalanceReportTest" time="31.397" errors="0" timestamp="5 Jul 2019 14:13:52 GMT">
  <testcase classname="com.nomisma.scriptsAccountingScenarios.VerifyPLTotalTrialBalanceReportTest" name="VerifyPLTotalTrialBalanceReport" time="24.233">
    <failure type="java.lang.AssertionError" message="Failed to verify value of Total expected [£0.00] but found [£140.03]">
      <![CDATA[java.lang.AssertionError: Failed to verify value of Total expected [£0.00] but found [£140.03]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.nomisma.pom.AccountingScenarios.VerifyValues(AccountingScenarios.java:199)
	at com.nomisma.pom.AccountingScenarios.VerifyPLTotalTrialBalanceReport(AccountingScenarios.java:232)
	at com.nomisma.scriptsAccountingScenarios.VerifyPLTotalTrialBalanceReportTest.VerifyPLTotalTrialBalanceReport(VerifyPLTotalTrialBalanceReportTest.java:39)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyPLTotalTrialBalanceReport -->
</testsuite> <!-- 144. AccountingReports  - VerifyPLTotalTrialBalanceReportTest -->
